trainer: paddleocr
repo_path: third_party/PaddleOCR
config_path: configs/rec/PP-OCRv4/PP-OCRv4_server_rec.yml
output_dir: vin_ocr_outputs/paddleocr
metrics_file: vin_ocr_outputs/paddleocr/metrics.json
repo_revision: ""
pretrained_model: "https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv4_server_rec_pretrained.pdparams"
export_onnx: true
onnx_output: vin_ocr_outputs/paddleocr/export.onnx